package com.github.semanticgit.ui

import androidx.compose.runtime.staticCompositionLocalOf

data class Strings(
    val appTitle: String,
    val navRepository: String,
    val navEntity: String,
    val navCommit: String,
    val navHistory: String,
    val navTools: String,
    val navSettings: String,
    val titlebarToggleLight: String,
    val titlebarToggleDark: String,
    val titlebarMinimize: String,
    val titlebarMaximize: String,
    val titlebarClose: String,
    val repoSelectPlaceholder: String,
    val repoSelectFolder: String,
    val repoNoRepoSelected: String,
    val currentRepository: String,
    val noRepositorySelected: String,
    val repoAnalyzing: String,
    val repoAnalysisFailed: String,
    val repoOperationDistribution: String,
    val repoNatureDistribution: String,
    val repoTotalCommits: String,
    val repoAnalysisStatus: String,
    // RepoPage - analysis config & button
    val repoClickToStart: String,
    val repoStartAnalysis: String,
    val repoAnalyzingButton: String,
    val repoReanalyzeConfigChanged: String,
    val repoReanalyzePrefix: String,
    val repoSelectFolderContentDesc: String,
    val repoAnalysisConfigTitle: String,
    val repoAnalysisConfigCollapse: String,
    val repoAnalysisConfigExpand: String,
    val repoAnalysisModeSection: String,
    val repoAnalysisModeFull: String,
    val repoAnalysisModeIncremental: String,
    val repoAnalysisModeFullDesc: String,
    val repoAnalysisModeIncrementalDesc: String,
    val repoParseConfigSection: String,
    val repoParseConfigHint: String,
    val repoFileTimeoutLabel: String,
    val repoMaxParseSizeLabel: String,
    val repoMaxRegexSizeLabel: String,
    val repoAnalyzingPhase1: String,
    val repoAnalyzingPhase2: String,
    val repoAnalyzingPhase3: String,
    val repoAnalyzingPhase4: String,
    val repoElapsedTime: String,
    val repoWaitPatiently: String,
    // Commit page
    val commitTopologyGraph: String,
    val commitSearchPlaceholder: String,
    val commitTotalCount: String,
    val commitLoading: String,
    val commitAnalysisFailedTitle: String,
    val commitAnalysisFailedHint: String,
    val commitClickDetailHint: String,
    val commitDetail: String,
    val commitNoStatsData: String,
    val commitFailedToLoad: String,
    // Author page
    val authorNoStatsData: String,
    val authorMatchedCount: String,
    // Entity Analysis
    val entityAnalysis: String,
    val searchEntity: String,
    val searchEntityPlaceholder: String,
    val selectBranch: String,
    val startQuery: String,
    val querying: String,
    val reset: String,
    val pleaseInputEntityName: String,
    val pleaseSelectBranch: String,
    val entityChangeHistory: String,
    val totalChanges: String,
    val noEntityHistoryFound: String,
    val noMatchingEntities: String,
    val dagGraphView: String,
    val flatListView: String,
    val traversalDfs: String,
    val traversalBfs: String,
    val searchHistory: String,
    val clearSearchHistory: String,
    val dbFileLoad: String,
    // Author Portrait
    val authorPortrait: String,
    val navAuthorPortrait: String,
    val searchAuthorPlaceholder: String,
    val authorOperationDistribution: String,
    val authorNatureDistribution: String,
    val noAuthorsFound: String,
    val totalAuthors: String,
    val loadingAuthors: String,
    // Settings
    val settingsTitle: String,
    val settingsLanguage: String,
    val settingsLanguageLabel: String,
    val settingsLanguageZh: String,
    val settingsLanguageEn: String,
    val settingsAppearance: String,
    val settingsAppearanceLabel: String,
    val settingsAppearanceLight: String,
    val settingsAppearanceDark: String,
    val settingsAbout: String,
    val settingsAboutVersion: String,
    val settingsAboutDesc: String,


    val entityOperationDistribution: String,
    val entityNatureDistribution: String,
    val elapsedTime: String,
    val estimatedRemaining: String,
    val loadDbFile: String,
    val selectDbFile: String,
    val loadFromDb: String,
    val dbFileLoaded: String,
    val failedToLoadDb: String,
    // DB Storage Settings
    val settingsDbStorage: String,
    val settingsDbStoragePath: String,
    val settingsDbStorageBrowse: String,
    val settingsDbFilenameFormat: String,
    val settingsDbFilenameFormatHint: String,
    val settingsDbResetDefault: String
)

val ZhStrings = Strings(
    appTitle = "SemanticGit",
    navRepository = "仓库",
    navEntity = "实体",
    navCommit = "提交",
    navHistory = "历史",
    navTools = "工具",
    navSettings = "设置",
    titlebarToggleLight = "切换浅色主题",
    titlebarToggleDark = "切换深色主题",
    titlebarMinimize = "最小化",
    titlebarMaximize = "最大化",
    titlebarClose = "关闭",
    repoSelectPlaceholder = "选择仓库文件夹...",
    repoSelectFolder = "选择文件夹",
    repoNoRepoSelected = "请选择一个仓库文件夹",
    currentRepository = "当前仓库",
    noRepositorySelected = "未选择仓库",
    repoAnalyzing = "正在分析仓库...",
    repoAnalysisFailed = "分析失败",
    repoOperationDistribution = "操作类型分布",
    repoNatureDistribution = "变更性质分布",
    repoTotalCommits = "总提交数",
    repoAnalysisStatus = "分析状态",
    // RepoPage - analysis config & button
    repoClickToStart = "点击「开始分析」查看结果",
    repoStartAnalysis = "开始分析",
    repoAnalyzingButton = "分析中...",
    repoReanalyzeConfigChanged = "重新分析（配置已变更）",
    repoReanalyzePrefix = "重新分析",
    repoSelectFolderContentDesc = "选择仓库文件夹",
    repoAnalysisConfigTitle = "分析配置",
    repoAnalysisConfigCollapse = "收起配置",
    repoAnalysisConfigExpand = "展开配置",
    repoAnalysisModeSection = "分析模式",
    repoAnalysisModeFull = "全量分析",
    repoAnalysisModeIncremental = "增量分析",
    repoAnalysisModeFullDesc = "重新分析所有提交，忽略已有数据",
    repoAnalysisModeIncrementalDesc = "仅分析上次分析之后的新提交",
    repoParseConfigSection = "解析配置",
    repoParseConfigHint = "修改后需点击「开始分析」生效",
    repoFileTimeoutLabel = "单文件解析超时（毫秒）",
    repoMaxParseSizeLabel = "超过此大小走文件级兜底（MB）",
    repoMaxRegexSizeLabel = "正则降级最大文件大小（MB）",
    repoAnalyzingPhase1 = "正在读取仓库...",
    repoAnalyzingPhase2 = "正在解析文件...",
    repoAnalyzingPhase3 = "正在统计变更...",
    repoAnalyzingPhase4 = "正在生成图表...",
    repoElapsedTime = "已用时：{0} 秒",
    repoWaitPatiently = "分析时间取决于仓库大小，请耐心等待",
    // Commit page
    commitTopologyGraph = "提交拓扑图",
    commitSearchPlaceholder = "输入提交哈希或消息搜索...",
    commitTotalCount = "总提交数: {0}，匹配 {1} 条",
    commitLoading = "加载中...",
    commitAnalysisFailedTitle = "未能分析提交",
    commitAnalysisFailedHint = "请先分析仓库或检查数据库是否已加载",
    commitClickDetailHint = "点击提交节点查看详情",
    commitDetail = "提交详情",
    commitNoStatsData = "暂无变更统计",
    commitFailedToLoad = "加载提交失败",
    // Author page
    authorNoStatsData = "暂无统计数据",
    authorMatchedCount = "匹配 {0} 位",
    // Entity Analysis
    entityAnalysis = "实体变更分析",
    searchEntity = "搜索实体（全限定名）",
    searchEntityPlaceholder = "输入实体名搜索...",
    selectBranch = "选择分支/Ref",
    startQuery = "查询",
    querying = "查询中...",
    reset = "重置",
    pleaseInputEntityName = "请输入实体名称",
    pleaseSelectBranch = "请选择分支",
    entityChangeHistory = "实体变更历史",
    totalChanges = "总变更数",
    noEntityHistoryFound = "未找到该实体的变更历史",
    noMatchingEntities = "无匹配的实体",
    dagGraphView = "DAG 图谱视图",
    flatListView = "扁平列表视图",
    traversalDfs = "DFS (深度优先)",
    traversalBfs = "BFS (广度优先)",
    searchHistory = "搜索历史",
    clearSearchHistory = "清空历史",
    dbFileLoad = "从数据库加载",
    // Author Portrait
    authorPortrait = "作者画像",
    navAuthorPortrait = "作者",
    searchAuthorPlaceholder = "输入作者名搜索...",
    authorOperationDistribution = "操作类型分布",
    authorNatureDistribution = "变更性质分布",
    noAuthorsFound = "未找到作者信息",
    totalAuthors = "作者总数",
    loadingAuthors = "加载中...",
    // Settings
    settingsTitle = "设置",
    settingsLanguage = "语言",
    settingsLanguageLabel = "界面语言",
    settingsLanguageZh = "中文",
    settingsLanguageEn = "English",
    settingsAppearance = "外观",
    settingsAppearanceLabel = "主题模式",
    settingsAppearanceLight = "浅色模式",
    settingsAppearanceDark = "深色模式",
    settingsAbout = "关于",
    settingsAboutVersion = "版本: 1.0.0",
    settingsAboutDesc = "SemanticGit - 基于语义分析的 Git 可视化工具",


    entityOperationDistribution = "实体变更操作分布",
    entityNatureDistribution = "实体变更性质分布",
    elapsedTime = "已用时",
    estimatedRemaining = "预计剩余",
    loadDbFile = "加载数据库文件",
    selectDbFile = "选择数据库文件",
    loadFromDb = "从数据库加载",
    dbFileLoaded = "数据库文件已加载",
    failedToLoadDb = "加载数据库文件失败",
    settingsDbStorage = "数据库存储",
    settingsDbStoragePath = "存储路径",
    settingsDbStorageBrowse = "浏览...",
    settingsDbFilenameFormat = "文件名格式",
    settingsDbFilenameFormatHint = $$"可用变量：${name}（仓库名）、${hash}（路径哈希）、${time}（时间戳）",
    settingsDbResetDefault = "恢复默认"
)

val EnStrings = Strings(
    appTitle = "SemanticGit",
    navRepository = "Repository",
    navEntity = "Entity",
    navCommit = "Commit",
    navHistory = "History",
    navTools = "Tools",
    navSettings = "Settings",
    titlebarToggleLight = "Switch to Light Theme",
    titlebarToggleDark = "Switch to Dark Theme",
    titlebarMinimize = "Minimize",
    titlebarMaximize = "Maximize",
    titlebarClose = "Close",
    repoSelectPlaceholder = "Select repository folder...",
    repoSelectFolder = "Select Folder",
    repoNoRepoSelected = "Please select a repository folder",
    currentRepository = "Current Repository",
    noRepositorySelected = "No Repository Selected",
    repoAnalyzing = "Analyzing repository...",
    repoAnalysisFailed = "Analysis failed",
    repoOperationDistribution = "Operation Distribution",
    repoNatureDistribution = "Change Nature Distribution",
    repoTotalCommits = "Total Commits",
    repoAnalysisStatus = "Analysis Status",
    // RepoPage - analysis config & button
    repoClickToStart = "Click \"Start Analysis\" to view results",
    repoStartAnalysis = "Start Analysis",
    repoAnalyzingButton = "Analyzing...",
    repoReanalyzeConfigChanged = "Reanalyze (Config Changed)",
    repoReanalyzePrefix = "Reanalyze",
    repoSelectFolderContentDesc = "Select Repository Folder",
    repoAnalysisConfigTitle = "Analysis Config",
    repoAnalysisConfigCollapse = "Collapse Config",
    repoAnalysisConfigExpand = "Expand Config",
    repoAnalysisModeSection = "Analysis Mode",
    repoAnalysisModeFull = "Full Analysis",
    repoAnalysisModeIncremental = "Incremental Analysis",
    repoAnalysisModeFullDesc = "Reanalyze all commits, ignoring existing data",
    repoAnalysisModeIncrementalDesc = "Only analyze new commits since last analysis",
    repoParseConfigSection = "Parse Config",
    repoParseConfigHint = "Changes take effect after clicking \"Start Analysis\"",
    repoFileTimeoutLabel = "Single File Parse Timeout (ms)",
    repoMaxParseSizeLabel = "Max File Size for AST Parsing (MB)",
    repoMaxRegexSizeLabel = "Max File Size for Regex Fallback (MB)",
    repoAnalyzingPhase1 = "Reading repository...",
    repoAnalyzingPhase2 = "Parsing files...",
    repoAnalyzingPhase3 = "Computing statistics...",
    repoAnalyzingPhase4 = "Generating charts...",
    repoElapsedTime = "Elapsed: {0} sec",
    repoWaitPatiently = "Analysis time depends on repository size, please wait",
    // Commit page
    commitTopologyGraph = "Commit Topology Graph",
    commitSearchPlaceholder = "Search by commit hash or message...",
    commitTotalCount = "Total: {0}, Matched: {1}",
    commitLoading = "Loading...",
    commitAnalysisFailedTitle = "Failed to analyze commits",
    commitAnalysisFailedHint = "Please analyze the repository first or check if the database is loaded",
    commitClickDetailHint = "Click a commit node to view details",
    commitDetail = "Commit Details",
    commitNoStatsData = "No change statistics",
    commitFailedToLoad = "Failed to load commits",
    // Author page
    authorNoStatsData = "No statistics data",
    authorMatchedCount = "Matched {0}",
    // Entity Analysis
    entityAnalysis = "Entity Tracking Analysis",
    searchEntity = "Search Entity (FQN)",
    searchEntityPlaceholder = "Type entity name...",
    selectBranch = "Select Branch/Ref",
    startQuery = "Start Query",
    querying = "Querying...",
    reset = "Reset",
    pleaseInputEntityName = "Please enter entity name",
    pleaseSelectBranch = "Please select a branch",
    entityChangeHistory = "Entity Change History",
    totalChanges = "Total Changes",
    noEntityHistoryFound = "No change history found for this entity",
    noMatchingEntities = "No matching entities",
    dagGraphView = "DAG Graph View",
    flatListView = "Flat List View",
    traversalDfs = "DFS (Depth First)",
    traversalBfs = "BFS (Breadth First)",
    searchHistory = "Search History",
    clearSearchHistory = "Clear History",
    dbFileLoad = "Load from Database",
    // Author Portrait
    authorPortrait = "Author Portrait",
    navAuthorPortrait = "Authors",
    searchAuthorPlaceholder = "Search author name...",
    authorOperationDistribution = "Operation Distribution",
    authorNatureDistribution = "Change Nature Distribution",
    noAuthorsFound = "No authors found",
    totalAuthors = "Total Authors",
    loadingAuthors = "Loading...",
    // Settings
    settingsTitle = "Settings",
    settingsLanguage = "Language",
    settingsLanguageLabel = "Interface Language",
    settingsLanguageZh = "中文",
    settingsLanguageEn = "English",
    settingsAppearance = "Appearance",
    settingsAppearanceLabel = "Theme Mode",
    settingsAppearanceLight = "Light Mode",
    settingsAppearanceDark = "Dark Mode",
    settingsAbout = "About",
    settingsAboutVersion = "Version: 1.0.0",
    settingsAboutDesc = "SemanticGit - Git Visualization Tool Based on Semantic Analysis",


    entityOperationDistribution = "Entity Operation Distribution",
    entityNatureDistribution = "Entity Change Nature Distribution",
    elapsedTime = "Elapsed",
    estimatedRemaining = "ETA",
    loadDbFile = "Load Database File",
    selectDbFile = "Select Database File",
    loadFromDb = "Load from DB",
    dbFileLoaded = "Database file loaded",
    failedToLoadDb = "Failed to load database file",
    settingsDbStorage = "Database Storage",
    settingsDbStoragePath = "Storage Path",
    settingsDbStorageBrowse = "Browse...",
    settingsDbFilenameFormat = "Filename Format",
    settingsDbFilenameFormatHint = $$"Available placeholders: ${name} (repo name), ${time} (timestamp)",
    settingsDbResetDefault = "Reset Default"
)

val LocalStrings = staticCompositionLocalOf { ZhStrings }
